# 開発環境用のDocker Compose設定
# `docker-compose up` を実行すると自動的に読み込まれます

version: '3.8'

services:
  web:
    build:
      target: builder
    environment:
      # 開発環境設定
      RAILS_ENV: development
      RAILS_LOG_LEVEL: debug
      RAILS_LOG_TO_STDOUT: true
      
      # 開発用のActivityPub設定
      ACTIVITYPUB_PROTOCOL: http
      
      # 開発時はS3を無効化
      S3_ENABLED: false
      
    volumes:
      # 開発時はライブリロード用にソースコードをマウント
      - .:/app:cached
      - /app/node_modules
      - /app/tmp
      - bundle_cache:/usr/local/bundle
      
      # 開発時はログをローカルに出力
      - ./log:/app/log
      - ./storage:/app/storage
      
    ports:
      - "3000:3000"
      
    # 開発時はリソース制限を緩める
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 1G

volumes:
  bundle_cache:
    driver: local