services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    volumes:
      # For development: mount source for live editing
      - .:/app
      - node_modules:/app/node_modules
      # Persistent storage
      - letter_storage:/app/storage
      - letter_logs:/app/log
      - letter_uploads:/app/public/uploads
    env_file:
      - .env
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/up"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  node_modules:
  letter_storage:
  letter_logs:
  letter_uploads:
