version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      # ActivityPub Configuration
      ACTIVITYPUB_DOMAIN: ${ACTIVITYPUB_DOMAIN:-localhost:3000}
      ACTIVITYPUB_PROTOCOL: ${ACTIVITYPUB_PROTOCOL:-http}
      
      # Instance Configuration
      INSTANCE_NAME: ${INSTANCE_NAME:-letter}
      INSTANCE_DESCRIPTION: ${INSTANCE_DESCRIPTION:-General Letter Publication System based on ActivityPub}
      CONTACT_EMAIL: ${CONTACT_EMAIL:-admin@localhost}
      MAINTAINER_NAME: ${MAINTAINER_NAME:-letter Administrator}
      
      # Feature flags
      FEDERATION_ENABLED: ${FEDERATION_ENABLED:-true}
      
      # Object Storage Configuration (Cloudflare R2)
      S3_ENABLED: ${S3_ENABLED:-false}
      S3_ENDPOINT: ${S3_ENDPOINT:-}
      S3_BUCKET: ${S3_BUCKET:-}
      R2_ACCESS_KEY_ID: ${R2_ACCESS_KEY_ID:-}
      R2_SECRET_ACCESS_KEY: ${R2_SECRET_ACCESS_KEY:-}
      S3_REGION: ${S3_REGION:-auto}
      S3_PROTOCOL: ${S3_PROTOCOL:-https}
      S3_PERMISSION: ${S3_PERMISSION:-private}
      S3_FORCE_SINGLE_REQUEST: ${S3_FORCE_SINGLE_REQUEST:-true}
      S3_ALIAS_HOST: ${S3_ALIAS_HOST:-}
      
      # Rails Configuration
      RAILS_ENV: ${RAILS_ENV:-development}
      RAILS_LOG_LEVEL: ${RAILS_LOG_LEVEL:-info}
      
    volumes:
      # Database persistence
      - ./db:/app/db
      
      # Logs persistence
      - ./log:/app/log
      
      # Media files persistence
      - ./public/system:/app/public/system
      
      # Optional: Mount .env file if it exists
      - ./.env:/app/.env:ro
      
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/up"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Optional: Add volumes for explicit persistence
volumes:
  letter_db:
    driver: local
  letter_media:
    driver: local
  letter_logs:
    driver: local