default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 20 } %>
  timeout: 30000
  pragma:
    journal_mode: :wal
    synchronous: :normal
    cache_size: 20000
    foreign_keys: :on
    temp_store: :memory
    mmap_size: 268435456

development:
  <<: *default
  database: storage/development.sqlite3

test:
  <<: *default
  database: storage/test.sqlite3
  pragma:
    foreign_keys: :on

production:
  <<: *default
  database: storage/production.sqlite3
  pragma:
    journal_mode: :wal
    synchronous: :normal
    cache_size: 50000
    foreign_keys: :on
    temp_store: :memory
    mmap_size: 536870912
