---
instance_name: 一般書簡公衆化システム
instance_description: General Letter Publication System based on ActivityPuba
instance_contact_email: admin@localhosta
instance_maintainer: letter Administratora
blog_footer: General Letter Publication System based on ActivityPuba
background_color: "#fdfbfb"
