---
instance_name: 一般書簡公衆化システム
instance_description: General Letter Publication System based on ActivityPub
instance_contact_email: admin@localhost
instance_maintainer: letter Administrator
blog_footer: General Letter Publication System based on ActivityPub
background_color: "#fdfbfb"
